// app/javascript/components/backlogs/SprintCard.vue
<template>
  <div class="card mt-2 shadow-sm">
    <div v-if="isEdit" class="card-header px-3 py-2">
      <b-form ref="form" class="d-flex flex-row flex-wrap align-items-center justify-content-between mb-2" @submit.stop.prevent="handleSubmit">
        <h6 class="m-0 font-weight-bold text-primary">
          <b-form-input
            id="title-input"
            v-model="dirtySprint.title"
            required
            ref="titleInput"
            size="sm"
          />
        </h6>
        <div class="d-flex flex-row align-items-center">
          <date-range-picker
            ref="picker"
            :locale-data="localeData"
            :timePicker="false"
            :autoApply="true"
            v-model="dateRange"
            @update="updateValues"
          >
            <div slot="input" slot-scope="picker" style="min-width: 200px;">
              {{ picker.startDate | date }} - {{ picker.endDate | date }}
            </div>
          </date-range-picker>
        </div>
      </b-form>
      <div class="d-flex flex-wrap justify-content-end">
        <a href="#" @click="editDone(true)" class="btn rb-btn-s btn-primary mr-1" key="check-button">
          <i class="fas fa-check"></i> {{ $t('action.save') }}
        </a>
        <a href="#" @click="editDone(false)" class="btn rb-btn-s btn-secondary" key="ban-button">
          <i class="fas fa-ban"></i> {{ $t('action.cancel') }}
        </a>
      </div>
    </div>
    <div v-else class="card-header px-2 py-2 d-flex flex-wrap align-items-center justify-content-between">
      <h6 class="m-0 text-gray-700" @click="editEnter">{{ sprint.title }}</h6>
      <div class="d-flex flex-wrap align-items-center">
        <div class="mr-3" @click="editEnter">
          <div v-if="sprint.start_datetime" class="text-xs text-muted">
            <span>{{ sprint.start_datetime | date }}</span>
            <span><i class="fas fa-angle-right"></i></span>
            <span>{{ sprint.end_datetime | date }}</span>
          </div>
          <div v-else>
            <span class="text-muted text-xs">{{ $t('message.noPeriodSpecified') }}</span>
          </div>
        </div>
        <div class="mr-2">
          <a :href="`/projects/${projectId}/sprints/${sprint.id}/kanban`" class="btn rb-btn-s btn-link p-1 mr-1" key="kanban-button" v-b-tooltip.hover :title="$t('action.viewKanban')">
            <i class="fa fa-border-all"></i>
          </a>
          <a href="#" v-if="!sprint.closed" @click='editEnter' class="btn rb-btn-s btn-link p-1 mr-1" v-b-tooltip.hover :title="$t('action.editSprint')">
            <i class="fas fa-pen"></i>
          </a>
          <a href="#" v-if="!sprint.closed" @click='onClickCloseSprint' class="btn rb-btn-s btn-link p-1" v-b-tooltip.hover :title="$t('action.closeSprint')">
            <i class="far fa-calendar-check"></i>
          </a>
          <a href="#" v-if="sprint.closed" @click='onClickOpenSprint' class="btn rb-btn-s btn-link p-1" v-b-tooltip.hover :title="$t('action.openSprint')">
            <i class="fas fa-door-open"></i>
          </a>
        </div>
      </div>
    </div>
    <ul class="list-group list-group-flush rb-draggable">
      <VueDraggable
        class="draggable_area"
        :list="sprint.stories"
        v-bind="dragOptions"
        :emptyInsertThreshold="40"
        :data-sprint-id="sprint.id"
        @end="dragEnd">
        <StoryListItem v-for="story in searchStoryByKeyword(sprint.stories)" :key="story.id" :story="story" :data-story-id="story.id" />
        <li v-if="sprint.stories.length == 0" class="list-group-item rb-alert-primary px-3 py-2">
          <div class="d-flex align-items-center">
            <i class="fas fa-info-circle mr-1"></i> {{ $t('message.storyDoesNotExistsInSprint') }}
          </div>
        </li>
      </VueDraggable>
    </ul>
    <div v-if="sprint.stories.length > 0" class="card-footer bg-gray-100 px-2 py-1">
      <div class="row text-center">
        <div class="col-sm-12 col-md mb-0">
          <div class="d-flex">
            <div class="text-muted mr-2">{{ $t('title.progress')}}</div>
            <div>
              <strong>{{ doneStoriesLength }} / {{ totalStoriesLength }} ({{ progressPercent | numeral('0') }}%)</strong>
            </div>
          </div>
          <div class="progress progress-xs mt-2">
            <div class="progress-bar bg-success" role="progressbar"
              :style="{width: `${progressPercent}%`}" :aria-valuenow="progressPercent" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
        <div class="col-sm-12 col-md mb-0">
          <div class="d-flex justify-content-end">
            <div class="text-muted mr-2">{{ $t('title.totalStoryPoints') }}</div>
            <div>
              <strong>{{ totalSprintPoint | numeral('0.0') }} {{ $t('title.points') }}</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Vue from 'vue'
import vueNumeralFilter from 'vue-numeral-filter'
import { mapActions } from 'vuex'
import DateRangePicker from 'vue2-daterange-picker'
//you need to import the CSS manually (in case you want to override it)
import 'vue2-daterange-picker/dist/vue2-daterange-picker.css'
import VueDraggable from 'vuedraggable'
import StoryListItem from './StoryListItem'
import CustomMoment from '../../commons/custom-moment'
import moment from '../../commons/custom-moment'

Vue.use(vueNumeralFilter)

export default {
  name: 'SprintCard',
  components: {
    VueDraggable,
    DateRangePicker,
    StoryListItem
  },
  props: {
    sprint: Object,
    projectId: String,
    searchKeyword: String,
  },
  mounted () {
    this.dirtySprint = this.sprint
    this.dateRange = {
      startDate: this.sprint.start_datetime,
      endDate: this.sprint.end_datetime
    }
  },
  filters: {
    date (value) {
      if (!value)
        return ''

      let options = {year: 'numeric', month: 'numeric', day: 'numeric'};
      let m = moment(value)
      return Intl.DateTimeFormat('en-ZA', options).format(m)
    }
  },
  data() {
    return {
      isEdit: false,
      dateRange: {
        startDate: null,
        endDate: null
      },
      dirtySprint: {
        id: null,
        title: '',
        start_datetime: null,
        end_datetime: null
      }
    }
  },
  watch: {
    sprint: function (val, oldVal) {
      this.dirtySprint = Object.assign({}, this.sprint)
    }
  },
  methods: {
    editEnter() {
      if (this.sprint.closed) {
        return;
      }

      this.isEdit = true
      Vue.nextTick(() => {
        this.$refs.titleInput.focus()
      })
    },
    editDone(isSave) {
      this.isEdit = false
      if (isSave) {
        this.updateSprint({
          projectId: this.projectId,
          sprint: this.dirtySprint
        })
      }
    },
    onClickCloseSprint() {
      this.closeSprint({
        projectId: this.projectId,
        sprint: this.sprint
      })
    },
    onClickOpenSprint() {
      this.openSprint({
        projectId: this.projectId,
        sprint: this.sprint
      })
    },
    handleSubmit() {
      this.editDone(true)
    },
    updateValues() {
      this.dirtySprint.start_datetime = this.dateRange.startDate
      this.dirtySprint.end_datetime = this.dateRange.endDate
    },
    dragEnd($event) {
      const from = {
        sprintId: parseInt($event.from.dataset.sprintId),
        oldIndex: parseInt($event.oldIndex)
      }
      const to = {
        sprintId: parseInt($event.to.dataset.sprintId),
        newIndex: parseInt($event.newIndex)
      }
      const storyId = parseInt($event.item.dataset.storyId)

      this.updateStoryByDrag({
        projectId: this.projectId,
        from: from,
        to: to,
        storyId: storyId
      })
    },
    searchStoryByKeyword(stories) {
      if (this.searchKeyword == null) {
        return stories;
      }

      return stories.filter(story => {
        return this.searchKeyword.toLowerCase()
          .split(/\s+/)
          .map(query => {
            return (
              story.ticket_number_with_ticket_prefix.toLowerCase().indexOf(query) > -1
              || story.title.toLowerCase().indexOf(query) > -1
              || (story.tags && story.tags.some(tag => tag.name.toLowerCase().indexOf(query) > -1))
            )
          })
          .every(result => result === true)
      });
    },
    ...mapActions({
      updateSprint: 'updateSprint',
      updateStoryByDrag: 'updateStoryByDrag',
      closeSprint: 'closeSprint',
      openSprint: 'openSprint'
    })
  },
  computed: {
    dragOptions() {
      return {
        animation: 100,
        group: 'STORIES',
        ghostClass: 'ghost'
      }
    },
    localeData() {
      return {
        firstDay: 1,
        format: CustomMoment.localeData().longDateFormat('L')
      }
    },
    totalSprintPoint() {
      return this.sprint.stories.reduce((a, b) => {
        return a + b.point
      }, 0)
    },
    doneStoriesLength() {
      return this.sprint.stories.filter(story => story.is_done).length
    },
    totalStoriesLength() {
      return this.sprint.stories.length
    },
    progressPercent() {
      return ((this.doneStoriesLength / this.totalStoriesLength) * 100)
    }
  }
}
</script>

<style lang="scss" scoped>
@import '../../stylesheets/application.scss';

.no-move {
  transition: transform 0s;
}
.ghost {
  opacity: 0.5;
  /* background: #c8ebfb; */
}
.empty_area {
  min-height: 30px;
}
.rb-draggable {
  min-height: 30px;
}
.vue-daterange-picker ::v-deep .reportrange-text {
  @extend .form-control-sm;
}

li.rb-alert-primary {
  @extend .alert;
  @extend .alert-primary;
}

.progress-xs {
  height: 4px;
}
</style>

// app/javascript/components/react/Backlogs/SprintCard.tsx
import { useDroppable } from '@dnd-kit/core';
import {
  SortableContext,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Ban,
  CalendarCheck,
  Check,
  ChevronRight,
  DoorOpen,
  LayoutGrid,
  MoreHorizontal,
  Pencil,
} from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { DateRangePicker } from '~/components/ui/date-range-picker';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu';
import api from '~/lib/api';
import type { Sprint } from '../shared/types';
import StoryListItem from './StoryListItem';

interface Props {
  sprint: Sprint;
  projectId: string;
  searchKeyword: string;
  onOpenStoryModal: (storyId: number) => void;
  activeId: number | null;
}

export default function SprintCard({
  sprint,
  projectId,
  searchKeyword,
  onOpenStoryModal,
  activeId,
}: Props) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [isEdit, setIsEdit] = useState(false);
  const [title, setTitle] = useState(sprint.title);
  const [dateRange, setDateRange] = useState({
    from: sprint.start_datetime
      ? sprint.start_datetime.substring(0, 10)
      : (null as string | null),
    to: sprint.end_datetime
      ? sprint.end_datetime.substring(0, 10)
      : (null as string | null),
  });
  const titleRef = useRef<HTMLInputElement>(null);

  const { setNodeRef } = useDroppable({ id: `sprint-${sprint.id}` });

  useEffect(() => {
    setTitle(sprint.title);
    setDateRange({
      from: sprint.start_datetime
        ? sprint.start_datetime.substring(0, 10)
        : null,
      to: sprint.end_datetime ? sprint.end_datetime.substring(0, 10) : null,
    });
  }, [sprint]);

  const updateMutation = useMutation({
    mutationFn: (data: object) =>
      api.put(`/projects/${projectId}/sprints/${sprint.id}`, data),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: ['sprints', projectId] }),
    onError: () => toast.error(t('message.failedToUpdateSprint')),
  });

  const closeMutation = useMutation({
    mutationFn: () =>
      api.patch(`/projects/${projectId}/sprints/${sprint.id}`, {
        closed: true,
      }),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: ['sprints', projectId] }),
    onError: () => toast.error(t('message.failedToCloseSprint')),
  });

  const openMutation = useMutation({
    mutationFn: () =>
      api.patch(`/projects/${projectId}/sprints/${sprint.id}`, {
        closed: false,
      }),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: ['sprints', projectId] }),
    onError: () => toast.error(t('message.failedToOpenSprint')),
  });

  const editDone = (save: boolean) => {
    setIsEdit(false);
    if (save) {
      updateMutation.mutate({
        title,
        start_datetime: dateRange.from || null,
        end_datetime: dateRange.to || null,
      });
    } else {
      setTitle(sprint.title);
      setDateRange({
        from: sprint.start_datetime
          ? sprint.start_datetime.substring(0, 10)
          : null,
        to: sprint.end_datetime ? sprint.end_datetime.substring(0, 10) : null,
      });
    }
  };

  const filteredStories = searchKeyword
    ? sprint.stories.filter((s) => {
        const q = searchKeyword.toLowerCase();
        return (
          s.ticket_number_with_ticket_prefix.toLowerCase().includes(q) ||
          s.title.toLowerCase().includes(q) ||
          (s.tags ?? []).some((t) => t.name.toLowerCase().includes(q))
        );
      })
    : sprint.stories;

  const doneCount = sprint.stories.filter((s) => s.is_done).length;
  const totalCount = sprint.stories.length;
  const progressPct = totalCount > 0 ? (doneCount / totalCount) * 100 : 0;
  const totalPoints = sprint.stories.reduce(
    (acc, s) => acc + (s.point ?? 0),
    0,
  );

  const progressColor =
    progressPct === 100
      ? 'bg-green-500'
      : progressPct >= 50
        ? 'bg-blue-500'
        : 'bg-amber-400';

  const formatDate = (d: string | null) => {
    if (!d) return '';
    return new Date(d).toLocaleDateString('en-ZA');
  };

  return (
    <div
      className={`rounded-md border bg-card shadow-sm text-sm ${sprint.closed ? 'opacity-70' : ''}`}
    >
      {isEdit ? (
        <div className="border-b px-3 py-2">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              editDone(true);
            }}
            className="space-y-2"
          >
            <input
              ref={titleRef}
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required
              className="h-8 w-full rounded-md border border-input bg-background px-3 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            />
            <DateRangePicker
              from={dateRange.from}
              to={dateRange.to}
              onChange={(from, to) => setDateRange({ from, to })}
            />
            <div className="flex justify-end gap-1">
              <button
                type="submit"
                className="inline-flex items-center gap-1 h-7 cursor-pointer rounded bg-primary px-2 text-xs font-medium text-primary-foreground"
              >
                <Check size={14} /> {t('action.save')}
              </button>
              <button
                type="button"
                onClick={() => editDone(false)}
                className="inline-flex items-center gap-1 h-7 cursor-pointer rounded border border-input bg-background px-2 text-xs"
              >
                <Ban size={14} /> {t('action.cancel')}
              </button>
            </div>
          </form>
        </div>
      ) : (
        <div className="flex items-center justify-between gap-2 border-b px-3 py-2">
          <div className="group/sprint-title flex min-w-0 items-center gap-2">
            <span className="font-semibold truncate">{sprint.title}</span>
            {sprint.start_datetime ? (
              <span className="inline-flex items-center gap-0.5 text-xs text-muted-foreground shrink-0">
                {formatDate(sprint.start_datetime)}
                <ChevronRight size={12} />
                {formatDate(sprint.end_datetime)}
              </span>
            ) : (
              <span className="text-xs text-muted-foreground shrink-0">
                {t('message.noPeriodSpecified')}
              </span>
            )}
            {!sprint.closed && (
              <button
                type="button"
                onClick={() => {
                  setIsEdit(true);
                  setTimeout(() => titleRef.current?.focus(), 50);
                }}
                className="shrink-0 cursor-pointer opacity-0 transition-opacity group-hover/sprint-title:opacity-40 hover:!opacity-100"
              >
                <Pencil size={14} />
              </button>
            )}
          </div>
          <div className="flex shrink-0 items-center gap-1">
            <a
              href={`/projects/${projectId}/sprints/${sprint.id}/kanban`}
              className="inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground"
            >
              <LayoutGrid size={16} />
            </a>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <button
                  type="button"
                  className="shrink-0 inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground"
                >
                  <MoreHorizontal size={16} />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem asChild>
                  <a
                    href={`/projects/${projectId}/sprints/${sprint.id}/kanban`}
                    className="inline-flex items-center gap-2"
                  >
                    <LayoutGrid size={14} />
                    {t('action.viewKanban')}
                  </a>
                </DropdownMenuItem>
                {!sprint.closed && (
                  <>
                    <DropdownMenuItem
                      onClick={() => {
                        setIsEdit(true);
                        setTimeout(() => titleRef.current?.focus(), 50);
                      }}
                    >
                      <Pencil size={14} />
                      {t('action.editSprint')}
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => closeMutation.mutate()}>
                      <CalendarCheck size={14} />
                      {t('action.closeSprint')}
                    </DropdownMenuItem>
                  </>
                )}
                {sprint.closed && (
                  <DropdownMenuItem onClick={() => openMutation.mutate()}>
                    <DoorOpen size={14} />
                    {t('action.openSprint')}
                  </DropdownMenuItem>
                )}
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      )}

      <ul
        ref={setNodeRef}
        className={`divide-y${filteredStories.length === 0 ? ' min-h-[48px]' : ''}`}
      >
        <SortableContext
          items={sprint.stories.map((s) => s.id)}
          strategy={verticalListSortingStrategy}
        >
          {filteredStories.map((story) => (
            <StoryListItem
              key={story.id}
              story={story}
              projectId={projectId}
              onOpenModal={onOpenStoryModal}
              isDraggingActive={activeId === story.id}
            />
          ))}
        </SortableContext>
        {sprint.stories.length === 0 && (
          <li className="flex flex-col items-center justify-center gap-1 px-3 py-6 text-xs text-muted-foreground border-2 border-dashed border-muted m-2 rounded-md">
            <span>{t('message.storyDoesNotExistsInSprint')}</span>
          </li>
        )}
      </ul>

      {sprint.stories.length > 0 && (
        <div className="border-t bg-muted/20 px-3 py-2 text-xs">
          <div className="flex items-center justify-between mb-1.5">
            <span className="text-muted-foreground">
              {t('title.progress')}{' '}
              <span className="font-medium text-foreground">
                {doneCount} / {totalCount} ({Math.round(progressPct)}%)
              </span>
            </span>
            <span className="text-muted-foreground">
              {t('title.totalStoryPoints')}{' '}
              <span className="font-medium text-foreground">
                {totalPoints.toFixed(1)} {t('title.points')}
              </span>
            </span>
          </div>
          <div className="h-2 w-full rounded-full bg-muted">
            <div
              className={`h-2 rounded-full transition-all ${progressColor}`}
              style={{ width: `${progressPct}%` }}
            />
          </div>
        </div>
      )}
    </div>
  );
}
