// app/javascript/components/backlogs/StoryListItem.vue
<template>
  <li class="list-group-item p-2" :style="backgroundColor">
    <div v-if="!isEdit">
      <div
        class="d-flex justify-content-between align-items-center rb-story-list-font"
        :style="idealTextColorForItem">
        <router-link :id="`popover-story-${story.id}`" :to="createStoryPath" class="badge badge-secondary bg-white badge-outlined rb-badge-radius p-1 mr-2">
          {{story.ticket_number_with_ticket_prefix}}
        </router-link>
        <div class="d-block text-truncate w-100 mr-2" :title="story.title">
          <s v-if="story.is_done" @click="onClickTitle">{{story.title}}</s>
          <span v-else @click="onClickTitle">{{story.title}}</span>
        </div>
        <span @click="onClickPoint">
          {{ story.point | numeral('0.0') }}
        </span>
      </div>
      <div class="mt-1" v-if="story.tags && story.tags.length > 0">
        <span class="rb-tag mr-1" v-for="tag in story.tags" :key="tag.id">
          {{ tag.name }}
        </span>
      </div>
    </div>
    <div v-else>
      <b-form @submit.stop.prevent="editDone(true)">
        <div class="d-flex justify-content-between align-items-center mb-2 rb-story-list-font">
          <router-link :to="createStoryPath" class="badge badge-secondary bg-white badge-outlined rb-badge-radius p-1 mr-2">
            {{story.ticket_number_with_ticket_prefix}}
          </router-link>
          <span class="text-monospace d-block text-truncate w-100 mr-2">
            <b-form-input size="sm" v-model="story.title" ref="storyTitle" />
          </span>
          <span>
            <b-form-input size="sm" type="number" v-model="story.point" step="0.5" ref="storyPoint" />
          </span>
        </div>
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn rb-btn-xs btn-primary mr-1" key="check-button">
            <i class="fas fa-check"></i> {{ $t('action.save') }}
          </button>
          <a href="#" @click="editDone(false)" class="btn rb-btn-xs btn-secondary" key="ban-button">
            <i class="fas fa-ban"></i> {{ $t('action.cancel') }}
          </a>
        </div>
      </b-form>
    </div>

    <b-popover :target="`popover-story-${story.id}`" triggers="hover" placement="right" delay="500">
      <dl>
        <dt>{{ $t('ticket.title') }}</dt>
        <dd>{{ story.title }}</dd>
        <dt>{{ $t('ticket.body') }}</dt>
        <dd><MarkdownText :content="story.body" /></dd>
      </dl>
    </b-popover>
  </li>
</template>

<script>
import Vue from 'vue'
import vueNumeralFilter from 'vue-numeral-filter'
import MarkdownText from '../MarkdownText'
import { mapMutations, mapActions } from 'vuex';
import ColorUtils from '../../mixins/colorUtils'

Vue.use(vueNumeralFilter)

export default {
  name: 'StoryListItem',
  components: {
    MarkdownText
  },
  mixins: [
    ColorUtils
  ],
  props: {
    story: Object
  },
  data() {
    return {
      isEdit: false
    }
  },
  computed: {
    createStoryPath() {
      return `/stories/${this.story.id}`
    },
    backgroundColor() {
      let color = '#ffffff'
      if (this.story.project_ticket_category) {
        color = this.story.project_ticket_category.color
      }

      return {
        "background-color": color
      }
    },
    idealTextColorForItem() {
      let color = '#ffffff'
      if (this.story.project_ticket_category) {
        color = this.story.project_ticket_category.color;
      }

      return {
        color: this.idealTextColor(color)
      }
    }
  },
  methods: {
    onClickTitle() {
      this.isEdit = true

      this.$nextTick(() => {
        this.$refs.storyTitle.focus()
      })
    },
    onClickPoint() {
      this.isEdit = true

      this.$nextTick(() => {
        this.$refs.storyPoint.focus()
      })
    },
    editDone(isSave) {
      this.isEdit = false
      if (isSave) {
        this.updateStory({
          projectId: this.story.project_id,
          story: this.story
        })
      }
    },
    ...mapActions('Stories', {
      updateStory: 'updateStory'
    })
  }
}
</script>

<style>
.rb-story-list-font {
  font-weight: 500 !important;
}
</style>

// app/javascript/components/react/Backlogs/StoryListItem.tsx
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Ban, Check, GripVertical, Pencil } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '~/components/ui/tooltip';
import api from '~/lib/api';
import { idealTextColor } from '../shared/colorUtils';
import type { Story } from '../shared/types';

interface Props {
  story: Story;
  projectId: string;
  onOpenModal: (storyId: number) => void;
  isDraggingActive?: boolean;
}

export default function StoryListItem({
  story,
  projectId,
  onOpenModal,
  isDraggingActive = false,
}: Props) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [isEdit, setIsEdit] = useState(false);
  const [title, setTitle] = useState(story.title);
  const [point, setPoint] = useState(
    story.point !== null && story.point !== undefined
      ? String(story.point)
      : '',
  );
  const titleRef = useRef<HTMLInputElement>(null);
  const pointRef = useRef<HTMLInputElement>(null);

  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: story.id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1,
  };

  useEffect(() => {
    setTitle(story.title);
    setPoint(
      story.point !== null && story.point !== undefined
        ? String(story.point)
        : '',
    );
  }, [story]);

  const updateMutation = useMutation({
    mutationFn: (data: object) =>
      api.patch(`/projects/${projectId}/stories/${story.id}`, data),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: ['sprints', projectId] }),
    onError: () => toast.error(t('message.failedToUpdateStory')),
  });

  const catColor = story.project_ticket_category?.color ?? '#ffffff';
  const textStyle = { color: idealTextColor(catColor) };
  const bgStyle = { backgroundColor: catColor };

  const editDone = (save: boolean) => {
    setIsEdit(false);
    if (save) {
      updateMutation.mutate({
        title,
        point: point === '' ? null : Number.parseFloat(point),
      });
    } else {
      setTitle(story.title);
      setPoint(
        story.point !== null && story.point !== undefined
          ? String(story.point)
          : '',
      );
    }
  };

  if (isDraggingActive) {
    return (
      <li
        ref={setNodeRef}
        style={style}
        className="list-none border-b border-dashed border-primary/40 bg-primary/5 px-2 py-1.5 min-h-[34px]"
      />
    );
  }

  return (
    <li
      ref={setNodeRef}
      style={{ ...style, ...bgStyle }}
      className={`list-none border-b px-2 py-1.5 text-sm${!isEdit ? ' cursor-grab active:cursor-grabbing' : ''}`}
      {...attributes}
      {...(!isEdit ? listeners : undefined)}
    >
      {isEdit ? (
        <form
          onSubmit={(e) => {
            e.preventDefault();
            editDone(true);
          }}
        >
          <div className="flex items-center gap-2">
            <span className="text-muted-foreground/40">
              <GripVertical size={12} />
            </span>
            <a
              href={`/${story.ticket_number_with_ticket_prefix}`}
              className="shrink-0 rounded border border-input bg-white px-1 py-0.5 font-mono text-xs"
              onClick={(e) => e.stopPropagation()}
            >
              {story.ticket_number_with_ticket_prefix}
            </a>
            <input
              ref={titleRef}
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="flex-1 rounded border border-input bg-background px-2 py-0.5"
            />
            <input
              ref={pointRef}
              type="number"
              value={point}
              onChange={(e) => setPoint(e.target.value)}
              step={0.5}
              className="w-16 rounded border border-input bg-background px-2 py-0.5"
            />
          </div>
          <div className="mt-1 flex justify-end gap-1">
            <button
              type="submit"
              className="inline-flex items-center gap-1 h-6 cursor-pointer rounded bg-primary px-2 text-xs text-primary-foreground"
            >
              <Check size={16} /> {t('action.save')}
            </button>
            <button
              type="button"
              onClick={() => editDone(false)}
              className="inline-flex items-center gap-1 h-6 cursor-pointer rounded border border-input bg-background px-2 text-xs"
            >
              <Ban size={16} /> {t('action.cancel')}
            </button>
          </div>
        </form>
      ) : (
        <div className="flex items-center gap-2" style={textStyle}>
          <span className="text-muted-foreground/40">
            <GripVertical size={12} />
          </span>
          <a
            href={`/${story.ticket_number_with_ticket_prefix}`}
            className="shrink-0 rounded border border-input bg-white px-1 py-0.5 font-mono text-xs text-gray-700"
            onPointerDown={(e) => e.stopPropagation()}
            onClick={(e) => {
              e.preventDefault();
              onOpenModal(story.id);
            }}
          >
            {story.ticket_number_with_ticket_prefix}
          </a>
          <span className="flex-1 truncate font-medium group/title flex items-center gap-1 min-w-0">
            <span className="truncate">
              {story.is_done ? <s>{story.title}</s> : story.title}
            </span>
            <TooltipProvider delayDuration={300}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <button
                    type="button"
                    className="shrink-0 cursor-pointer opacity-0 group-hover/title:opacity-60 hover:!opacity-100 transition-opacity"
                    onPointerDown={(e) => e.stopPropagation()}
                    onClick={() => {
                      setIsEdit(true);
                      setTimeout(() => titleRef.current?.focus(), 50);
                    }}
                  >
                    <Pencil size={12} />
                  </button>
                </TooltipTrigger>
                <TooltipContent>{story.title}</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </span>
          <button
            type="button"
            className="shrink-0 cursor-pointer"
            onPointerDown={(e) => e.stopPropagation()}
            onClick={() => {
              setIsEdit(true);
              setTimeout(() => pointRef.current?.focus(), 50);
            }}
          >
            {story.point !== null && story.point !== undefined
              ? Number(story.point).toFixed(1)
              : '-'}
          </button>
        </div>
      )}
      {story.tags && story.tags.length > 0 && (
        <div className="mt-0.5 flex flex-wrap gap-1 pl-5">
          {story.tags.map((tag) => (
            <span
              key={tag.id}
              className="rounded border border-input bg-muted px-1.5 py-0.5 text-xs"
            >
              {tag.name}
            </span>
          ))}
        </div>
      )}
    </li>
  );
}
